basyx:
  submodelregistry:
      authorization:
        enabled: true
        type: rbac
        rbac:
          file: /workspace/config/rbac_rules.json
spring:
  security:
    oauth2:
      resourceserver:
        jwt.issuer-uri: http://host.docker.internal:8080/realms/master