---
servlet:
  headers:
    - path: /**
      values:
        Access-Control-Allow-Origin: "*"
        Access-Control-Max-Age: 10000
    - path: /registry/shell-descriptors/search
      values:
        Access-Control-Allow-Origin: "*"
        Access-Control-Allow-Methods: POST,GET,OPTIONS
        Access-Control-Allow-Headers: Accept, Content-Type
      methods: 
        - OPTIONS
basyx:
  aasregistry:
      authorization:
        enabled: true
        type: rbac
        rbac:
          file: /workspace/config/rbac_rules.json
spring:
  security:
    oauth2:
      resourceserver:
        jwt.issuer-uri: http://host.docker.internal:8080/realms/master